import io
import zipfile
import json
import requests
from typing import List
from models.nanobanana import VisualVariant

class ZipManager:
    """
    ENOLA.AI DELIVERABLE BUNDLER: Nano Banana 2 Pipeline.
    Packages 4K artifacts into a professional ZIP deliverable for the user.
    """
    
    @staticmethod
    def create_nano_banana_bundle(variants: List[VisualVariant]) -> io.BytesIO:
        """
        Create a professional ZIP bundle for Nano Banana 2 variants.
        Structure:
        /Source (Clean High-Ref 4K)
        /Ad-Ready (Visuals with Metadata/Text Layers)
        Manifest.json (Token/Campaign Provenance)
        """
        zip_buffer = io.BytesIO()
        
        with zipfile.ZipFile(zip_buffer, "a", zipfile.ZIP_DEFLATED, False) as zip_file:
            # 1. Create Folder Structure and Write Files
            for i, variant in enumerate(variants):
                filename = f"variant_0{i+1}_{variant.variant_id}"
                
                # SIMULATION: In a production environment, we'd be writing the 4K buffers here.
                # For this prototype, we write a text manifest for each variant.
                
                # Folder: Source (Clean)
                zip_file.writestr(f"Source/{filename}_clean.png", f"4K_IMAGE_BUFFER_SIMULATION_FOR_{variant.image_url}")
                
                # Folder: Ad-Ready (Metadata Layer)
                ad_data = {
                    "headline": variant.headline,
                    "description": variant.description,
                    "style": variant.style_label,
                    "original_source": variant.image_url
                }
                zip_file.writestr(f"Ad-Ready/{filename}_final.png", f"AD_READY_LAMINATED_VISUAL_SIMULATION")
                zip_file.writestr(f"Ad-Ready/{filename}_metadata.json", json.dumps(ad_data, indent=2))

            # 2. Add Service Manifest (Enola.ai Proof of Quality)
            manifest = {
                "service": "Nano Banana 2 (Highest Tier)",
                "resolution": "3840x2160 (4K)",
                "variants_packed": len(variants),
                "generated_by": "Enola.ai Agentic Swarm",
                "disclaimer": "All visuals generated by specialized visual executors are optimized for social platform compliance."
            }
            zip_file.writestr("campaign_manifest.json", json.dumps(manifest, indent=2))

        zip_buffer.seek(0)
        return zip_buffer
